In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn import tree
from sklearn.tree import DecisionTreeClassifier

from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score

In [48]:
data = pd.read_csv("loan_approval.csv")
data

,name,city,income,credit_score,loan_amount,years_employed,points,loan_approved
0,Allison Hill,East Jill,113810,389,39698,27,50.0,False
1,Brandon Hall,New Jamesside,44592,729,15446,28,55.0,False
2,Rhonda Smith,Lake Roberto,33278,584,11189,13,45.0,False
3,Gabrielle Davis,West Melanieview,127196,344,48823,29,50.0,False
4,Valerie Gray,Mariastad,66048,496,47174,4,25.0,False
...,...,...,...,...,...,...,...,...
1995,James Schaefer,Robertton,92163,770,12251,13,85.0,True
1996,Diana Lin,New Frank,38799,635,48259,17,40.0,False
1997,Brandon Meyer,East Haley,41957,763,16752,5,60.0,True
1998,Jason Price,Adamland,139022,360,24031,35,55.0,False
1999,Nicole Brown,New Nathantown,41188,482,31397,6,20.0,False

In [49]:
data.isna().sum()

name              0
city              0
income            0
credit_score      0
loan_amount       0
years_employed    0
points            0
loan_approved     0
dtype: int64

In [50]:
data.describe()

              income  credit_score   loan_amount  years_employed       points
count    2000.000000   2000.000000   2000.000000     2000.000000  2000.000000
mean    90585.977000    573.946000  25308.503000       20.441000    56.680000
std     34487.874907    160.564945  14207.320147       11.777813    18.638033
min     30053.000000    300.000000   1022.000000        0.000000    10.000000
25%     61296.250000    433.000000  12748.750000       10.000000    45.000000
50%     90387.500000    576.000000  25661.500000       21.000000    55.000000
75%    120099.750000    715.000000  37380.500000       31.000000    70.000000
max    149964.000000    850.000000  49999.000000       40.000000   100.000000

In [51]:
data.drop(["name", "city"], axis=1, inplace=True)

In [52]:
data["loan_approved"] = (data["loan_approved"] == True).astype("int8")
data

      income  credit_score  loan_amount  years_employed  points  loan_approved
0     113810           389        39698              27    50.0              0
1      44592           729        15446              28    55.0              0
2      33278           584        11189              13    45.0              0
3     127196           344        48823              29    50.0              0
4      66048           496        47174               4    25.0              0
...      ...           ...          ...             ...     ...            ...
1995   92163           770        12251              13    85.0              1
1996   38799           635        48259              17    40.0              0
1997   41957           763        16752               5    60.0              1
1998  139022           360        24031              35    55.0              0
1999   41188           482        31397               6    20.0              0

[2000 rows x 6 columns]

In [53]:
data.groupby("points")["loan_approved"].mean()

points
10.0     0.0
15.0     0.0
20.0     0.0
25.0     0.0
30.0     0.0
35.0     0.0
40.0     0.0
45.0     0.0
50.0     0.0
55.0     0.0
60.0     1.0
65.0     1.0
70.0     1.0
75.0     1.0
80.0     1.0
85.0     1.0
90.0     1.0
95.0     1.0
100.0    1.0
Name: loan_approved, dtype: float64

In [54]:
x = data.drop(["loan_approved", "points"], axis=1).values
y = data["loan_approved"]

In [86]:
scores_test = []
scores_train = []
cv = KFold(n_splits=5, shuffle=True, random_state=42)
for train_ind, test_ind, in cv.split(x):
    x_train, x_test, y_train, y_test = x[train_ind], x[test_ind], y[train_ind], y[test_ind]
    model = DecisionTreeClassifier(max_depth=4, min_samples_split=2, min_samples_leaf=1, criterion="gini", random_state=42)
    model.fit(x_train, y_train)
    acc_test = accuracy_score(y_test, model.predict(x_test))
    acc_train = accuracy_score(y_train, model.predict(x_train))
    scores_test.append(acc_test)
    scores_train.append(acc_train)
print(f"Mean train: {np.mean(scores_train)} \nMean test: {np.mean(scores_test)}")

Mean train: 0.9515
Mean test: 0.9414999999999999